export const webConceptsQA = [
  {
    keywords: ["client", "server"],
    answer: `Client side - End-user devices, such as smartphones, desktop computers, and laptops. Server side - like hosting websites, managing emails, or storing files. JavaScript (JS) can be used as both a client-side and a server-side language. Client-side languages: HTML (structure), CSS (styling), and JavaScript (behavior) are used to run code in the user's web browser. Server-side languages: Python, PHP, Java, Ruby, Node.js (JavaScript runtime), and C# are common options that run on the web server to manage logic and data.`,
  },
  {
    keywords: ["Server-Sent Events", "SSE"],
    answer: `SSE is a way for the server to send real-time updates to the browser. It creates a connection between server and client. The connection stays open. The server keeps sending data automatically. It works only one way (Server → Client).`,
  },
  {
    keywords: ["ci/cd"],
    answer: `CI/CD is a process that automates building, testing, and deploying code. CI focuses on integrating and testing code changes, while CD focuses on automatically deploying the application. CI (Continuous Integration): CI means automatically testing and merging code whenever developers push changes. CD (Continuous Deployment): CD means automatically deploying the tested code to production or server. In simple words: CI automatically tests and builds the code. CD automatically deploys the code.`,
  },
  {
    keywords: ["restful api", "rest"],
    answer: `RESTful API is a way for two applications to communicate with each other over the internet. It follows REST (Representational State Transfer) principles and uses HTTP methods. Common HTTP methods: GET – used to fetch data. POST – used to create new data. PUT – used to update existing data. DELETE – used to remove data. REST APIs usually send and receive data in JSON format. They are widely used in web applications to connect the frontend and backend. In simple words: A RESTful API allows different applications to communicate using standard HTTP requests.`,
  },
  {
    keywords: ["json", "package-lock.json"],
    answer: `JSON stands for JavaScript Object Notation. It is a lightweight data format used to store and exchange data between server and client. Example: { "name": "Chaitanya", "age": 25 }. package-lock.json is automatically generated by npm. It locks the exact versions of installed dependencies so that every developer gets the same versions when installing packages. In simple words: JSON is used for data format, while package-lock.json locks dependency versions.`,
  },
  {
    keywords: ["graphQl"],
    answer: `GraphQL is a query language for APIs. It allows the client to request only the data it needs. It was developed by Meta Platforms. Main concepts: Query → Used to fetch data. Mutation → Used to create/update/delete data. Schema → Defines structure of API. Resolver → Handles request logic.`,
  },
  {
    keywords: ["diff rest and graphQl"],
    answer: `REST and GraphQL are two ways to communicate between client and server. REST uses multiple URLs (endpoints) to get different types of data. REST problems: 1. Over-fetching - Sometimes the API sends more data than we need. 2. Under-fetching - Sometimes one API does not give enough data. 3. Fixed response - Server decides what data will be returned. GraphQL uses a single endpoint. The client sends a query and decides exactly what data is needed. Advantages: 1. No over-fetching - Client requests only the fields it needs. 2. No under-fetching - Client can fetch related data in a single request. 3. Single endpoint - All requests go through one endpoint.`,
  },
  {
    keywords: ["agile"],
    answer: `Agile is a way of working where we develop the product in small parts, deliver frequently, and take continuous feedback from client or stakeholders. Instead of building everything at once, we build feature by feature and improve based on requirements. Waterfall is a development approach where the project flows in one direction like a waterfall — first requirements, then design, development, testing, and finally deployment. We cannot easily go back once a phase is completed.`,
  },
  {
    keywords: ["browser", "crp", "critical rendering path"],
    answer: `Critical Rendering Path means the steps the browser follows to show a webpage on the screen. 1. HTML -> DOM: Browser reads the HTML and creates the page structure. 2. CSS -> CSSOM: Browser reads CSS and understands how the page should look. 3. Render Tree: Browser combines DOM + CSSOM to know what elements should appear. 4. Layout: Browser calculates the exact position and size of each element. 5. Paint: Finally, the browser draws everything on the screen. To make it faster: Keep CSS files small, Put JavaScript at the bottom or use defer, Use minified CSS and JS files.`,
  },
  {
    keywords: ["security", "xss"],
    answer: `XSS is when a hacker tries to put a "bad script" into your website (like inside a comment box). If the website is not safe, that script can steal user data. To prevent this: React is smart—it automatically cleans the text before showing it on the screen. We should never use 'dangerouslySetInnerHTML' unless we really trust the data.`,
  },
  {
    keywords: ["security"],
    answer: `Security practices: Avoid storing sensitive data in localStorage. Prevent XSS attacks. Use HTTPS. Validate inputs. Use secure authentication tokens.`,
  },
  {
    keywords: ["accessibility"],
    answer: `Accessibility ensures the application can be used by people with disabilities. Use semantic HTML, proper labels, alt tags, ARIA roles, and keyboard navigation.`,
  },
  {
    keywords: ["micro frontend", "micro", "micro vs macro"],
    answer: `Micro Frontend is an architecture where a large frontend application is divided into small independent applications. Each part of the UI is built and managed by different teams and can be developed, tested, and deployed separately. Micro vs Macro (Task Queue in JavaScript): Microtask Queue runs immediately after the current code finishes and before the browser moves to the next event loop cycle. Examples: Promise.then(), Promise.catch(), queueMicrotask(), MutationObserver. Macrotask Queue is executed after microtasks are completed. Examples: setTimeout, setInterval, DOM events. JavaScript always executes all microtasks before moving to macrotasks.`,
  },
  {
    keywords: ["intercept", "axios", "security guard"],
    answer: `An Interceptor is like a Security Guard for your API calls. Imagine every time you leave your house (send a request), the guard checks if you have your ID card (Token). And every time you come back (receive a response), the guard checks if you are still allowed to enter. We use it to: Automatically add the "Token" to every API call. If the server says "Session Expired", the guard catches it and sends the user to the Login page instantly.`,
  },
  {
    keywords: ["debounce", "throttle"],
    answer: `Debouncing delays execution until user stops typing. Used in search inputs. Throttling limits execution to once in a given time. Used in scroll or resize events. Both improve performance.`,
  },
  {
    keywords: ["vitals", "speed", "lighthouse"],
    answer: `Web Vitals are like a Health Report for your website. Google looks at three main things: 1. LCP (Loading): How fast does the biggest image or text load? 2. FID (Interactivity): When I click a button, how fast does it react? 3. CLS (Stability): Does the page jump around while loading? I use a tool called Lighthouse in Chrome. It gives a score out of 100. If the score is low, I fix it by compressing images or removing heavy code.`,
  },
  {
    keywords: ["large application", "large"],
    answer: `For large applications: Use modular folder structure. Separate business logic and UI. Use reusable components. Maintain proper state management. Follow coding standards. Write unit tests. Use lazy loading and code splitting.`,
  },
  {
    keywords: ["Debounce Function"],
    answer: `Debouncing is a technique used to limit how often a function runs. It delays the execution of a function until after a certain time has passed since the last event. If the event keeps happening (like typing or scrolling), the timer resets and the function will run only once after the user stops. Why we use debounce: It helps improve performance and prevents unnecessary function calls. Common use cases: Search input API calls, Window resize events, Button click prevention. function debounce(fn, delay) { let timer; return function (...args) { clearTimeout(timer); timer = setTimeout(() => { fn(...args); }, delay); }; } In simple words: Debounce means delaying a function call until the user stops performing an action.`,
  },
  {
    keywords: ["5 seconds delay", "delay"],
    answer: `function delay() { return new Promise((resolve) => { setTimeout(() => { resolve(); }, 5000); }); } console.log("Start"); delay().then(() => { console.log("End"); });`,
  },
];
